package cn.linshenkx.halosyncserver;

import cn.hutool.core.io.FileUtil;
import com.sshtools.common.publickey.SshKeyPairGenerator;
import com.sshtools.common.publickey.SshKeyUtils;
import com.sshtools.common.ssh.SshException;
import com.sshtools.common.ssh.components.SshKeyPair;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

public class SshTest {

    @Test
    public void createKeyPair() throws IOException, SshException {
        SshKeyPair pair = SshKeyPairGenerator.generateKeyPair(SshKeyPairGenerator.SSH2_RSA, 2048);
        SshKeyUtils.createPublicKeyFile(pair.getPublicKey(),
                "Generated by Maverick Synergy", new File("key.pub"));
        SshKeyUtils.createPrivateKeyFile(pair, "123456", new File("key"));
    }

    @Test
    public void catPublicKey() {
        System.out.println(FileUtil.readString("D:\\Dev\\myProject\\haloSyncServer\\key.pub", StandardCharsets.UTF_8));
    }

}
